// Generated by CoffeeScript 1.4.0
var App, app, port;

App = module.exports = require('express');

app = App();

app.configure(function() {
  app.use(App["static"](__dirname + '/assets'));
  app.set('view engine', 'jade');
  app.set('view options', {
    layout: false
  });
  app.use(App.bodyParser());
  app.use(App.cookieParser());
  return app.locals.title = 'Angular on Express Application';
});

app.configure('development', function() {
  app.use(App.logger('dev'));
  return app.use(App.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

port = process.env.npm_package_config_port;

app.listen(port, function() {
  return console.log('Listening on ' + port + '\nPress CTRL-C to stop server.' + Date(Date.now()));
});

app.get('/', function(req, res) {
  return res.render('pages/index');
});

app.get('/index.html', function(req, res) {
  return res.render('pages/partials/index');
});
