
name: angular-on-express-app
version: 0.0.1

private: true



config:

  port: 8000
  url: http://localhost:8000



scripts:

  start: node index.js



dependencies:

  express: 3.x
  express-namespace: latest

  jade: latest



engines:
  node: ~0.8.x